In [5]:
'''
https://archive.ics.uci.edu/ml/datasets/Balance+Scale

Attribute Information:

1. Class Name: 3 (L, B, R) 
2. Left-Weight: 5 (1, 2, 3, 4, 5) 
3. Left-Distance: 5 (1, 2, 3, 4, 5) 
4. Right-Weight: 5 (1, 2, 3, 4, 5) 
5. Right-Distance: 5 (1, 2, 3, 4, 5)

Number of Instances: 625
L == 1
B == 2
R == 3
'''
import numpy as np

In [7]:
# x = entrada
# y = saida

x = np.genfromtxt('DataSets/balance-scale.data', delimiter=',', usecols=(1,2,3,4))
y = np.genfromtxt('DataSets/balance-scale.data', delimiter=',', usecols=(0))
    
print(len(x))
print(len(y))
print(x)
print(y)

625
625
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  2.]
 [ 1.  1.  1.  3.]
 ..., 
 [ 5.  5.  5.  3.]
 [ 5.  5.  5.  4.]
 [ 5.  5.  5.  5.]]
[ 2.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.
  3.  3.  3.  3.  3.  3.  3.  1.  2.  3.  3.  3.  2.  3.  3.  3.  3.  3.
  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  1.  1.  2.  3.
  3.  1.  3.  3.  3.  3.  2.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.
  3.  3.  3.  1.  1.  1.  2.  3.  1.  2.  3.  3.  3.  1.  3.  3.  3.  3.
  2.  3.  3.  3.  3.  3.  3.  3.  3.  3.  1.  1.  1.  1.  2.  1.  1.  3.
  3.  3.  1.  3.  3.  3.  3.  1.  3.  3.  3.  3.  2.  3.  3.  3.  3.  1.
  2.  3.  3.  3.  2.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.
  3.  3.  3.  3.  3.  3.  1.  1.  1.  2.  3.  1.  2.  3.  3.  3.  1.  3.
  3.  3.  3.  2.  3.  3.  3.  3.  3.  3.  3.  3.  3.  1.  1.  1.  1.  1.
  1.  1.  2.  3.  3.  1.  2.  3.  3.  3.  1.  3.  3.  3.  3.  1.  3.  3.
  3.  3.  1.  1.  1.  1.  1.  1.  1.  1.  2.  3.  1.  1.  3.  3.  3

In [9]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3, random_state=42)

In [11]:
print(len(x_train))
x_train

437


array([[ 2.,  4.,  1.,  5.],
       [ 1.,  4.,  3.,  4.],
       [ 5.,  1.,  5.,  3.],
       ..., 
       [ 3.,  1.,  5.,  1.],
       [ 4.,  3.,  3.,  1.],
       [ 1.,  5.,  1.,  3.]])

In [13]:
print(len(x_test))
x_test

188


array([[ 4.,  3.,  5.,  3.],
       [ 4.,  5.,  3.,  1.],
       [ 2.,  4.,  4.,  1.],
       [ 2.,  4.,  3.,  3.],
       [ 4.,  5.,  2.,  1.],
       [ 5.,  1.,  4.,  1.],
       [ 2.,  2.,  3.,  4.],
       [ 1.,  4.,  1.,  3.],
       [ 5.,  2.,  1.,  3.],
       [ 2.,  1.,  5.,  1.],
       [ 3.,  1.,  4.,  1.],
       [ 1.,  2.,  2.,  2.],
       [ 1.,  3.,  2.,  1.],
       [ 1.,  4.,  4.,  1.],
       [ 5.,  3.,  2.,  3.],
       [ 1.,  4.,  1.,  2.],
       [ 1.,  1.,  1.,  3.],
       [ 3.,  5.,  4.,  4.],
       [ 4.,  1.,  5.,  1.],
       [ 3.,  2.,  3.,  2.],
       [ 2.,  1.,  2.,  2.],
       [ 2.,  1.,  5.,  4.],
       [ 1.,  2.,  5.,  5.],
       [ 5.,  5.,  5.,  2.],
       [ 4.,  3.,  3.,  3.],
       [ 1.,  5.,  3.,  1.],
       [ 3.,  1.,  2.,  3.],
       [ 5.,  4.,  1.,  4.],
       [ 5.,  5.,  5.,  1.],
       [ 3.,  1.,  2.,  2.],
       [ 3.,  4.,  2.,  5.],
       [ 3.,  1.,  3.,  2.],
       [ 2.,  3.,  2.,  5.],
       [ 5.,  3.,  1.,  5.],
       [ 2.,  

In [21]:
x_test[0]

array([ 4.,  3.,  5.,  3.])

In [23]:
from sklearn.neighbors import KNeighborsClassifier as knc
knn = knc(n_neighbors=17,p=2)
knn.fit(x_train, y_train)
labels = knn.predict(x_test)
print(len(labels))
labels

188


array([ 1.,  1.,  1.,  1.,  1.,  1.,  3.,  1.,  1.,  3.,  3.,  3.,  1.,
        3.,  1.,  1.,  3.,  3.,  3.,  1.,  3.,  3.,  3.,  1.,  1.,  1.,
        3.,  1.,  1.,  1.,  1.,  3.,  3.,  1.,  3.,  1.,  1.,  1.,  1.,
        1.,  1.,  3.,  1.,  1.,  3.,  1.,  1.,  3.,  1.,  3.,  1.,  1.,
        3.,  3.,  1.,  1.,  3.,  1.,  1.,  1.,  1.,  1.,  3.,  3.,  1.,
        1.,  3.,  3.,  1.,  1.,  3.,  3.,  3.,  3.,  3.,  1.,  1.,  3.,
        1.,  3.,  3.,  3.,  3.,  1.,  3.,  1.,  1.,  1.,  3.,  1.,  1.,
        1.,  3.,  1.,  1.,  3.,  3.,  3.,  3.,  3.,  1.,  3.,  3.,  3.,
        1.,  1.,  1.,  3.,  3.,  1.,  3.,  1.,  3.,  3.,  1.,  3.,  1.,
        1.,  1.,  1.,  3.,  3.,  1.,  3.,  3.,  3.,  3.,  3.,  1.,  3.,
        1.,  1.,  1.,  3.,  1.,  1.,  1.,  3.,  1.,  1.,  1.,  1.,  3.,
        3.,  1.,  3.,  3.,  1.,  3.,  3.,  3.,  3.,  3.,  1.,  1.,  3.,
        1.,  1.,  3.,  1.,  1.,  3.,  3.,  1.,  1.,  1.,  3.,  1.,  3.,
        3.,  1.,  3.,  3.,  3.,  1.,  1.,  1.,  1.,  3.,  1.,  3

In [25]:
y_test

array([ 3.,  1.,  1.,  3.,  1.,  1.,  3.,  1.,  1.,  3.,  3.,  3.,  1.,
        2.,  1.,  1.,  3.,  3.,  3.,  2.,  3.,  3.,  3.,  1.,  1.,  1.,
        3.,  1.,  1.,  3.,  1.,  3.,  3.,  1.,  3.,  1.,  1.,  1.,  1.,
        3.,  2.,  3.,  3.,  1.,  3.,  2.,  2.,  3.,  2.,  3.,  1.,  1.,
        3.,  3.,  1.,  1.,  3.,  1.,  1.,  2.,  1.,  1.,  3.,  3.,  1.,
        1.,  3.,  3.,  1.,  1.,  3.,  3.,  3.,  3.,  3.,  1.,  1.,  3.,
        1.,  3.,  3.,  2.,  3.,  1.,  3.,  2.,  1.,  1.,  3.,  1.,  1.,
        1.,  3.,  1.,  1.,  3.,  3.,  3.,  3.,  3.,  1.,  2.,  3.,  3.,
        1.,  2.,  1.,  3.,  3.,  1.,  3.,  1.,  3.,  3.,  1.,  3.,  1.,
        1.,  1.,  1.,  3.,  3.,  1.,  3.,  3.,  3.,  3.,  3.,  2.,  3.,
        1.,  1.,  2.,  3.,  1.,  1.,  1.,  3.,  1.,  1.,  1.,  3.,  3.,
        3.,  1.,  3.,  3.,  1.,  3.,  3.,  3.,  3.,  3.,  1.,  3.,  3.,
        2.,  1.,  2.,  1.,  1.,  3.,  3.,  1.,  1.,  1.,  3.,  1.,  3.,
        2.,  1.,  3.,  3.,  3.,  2.,  1.,  1.,  1.,  3.,  1.,  3

In [27]:
np.sum(labels == y_test) # comparação
(labels == y_test).sum() # comparação

163

In [28]:
100 * np.sum(labels == y_test) / len(x_test) # porcentagem de acertos

86.702127659574472